services:
  api-gateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Dockerfile
    ports:
      - "5000:5000" # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GrpcServices__CurrencyService=https://currency-service:8101
    networks:
      - app-network

  currency-service:
    build:
      context: .
      dockerfile: src/CurrencyService/Dockerfile
    ports:
      - "8101:8101" # gRPC
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Kestrel__Endpoints__Grpc__Url=https://0.0.0.0:8101
      - Kestrel__Certificates__Default__Path=/app/Certificates/localhost.pfx
      - Kestrel__Certificates__Default__Password=yourpassword
    volumes:
      - /home/ds-1/Documents/Projects/Certificates:/app/Certificates:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
